import pandas as pd, json
D=pd.read_pickle('final.pkl')
n=len(D); A=(D.grade=='A').sum(); B=(D.grade=='B').sum(); C=(D.grade=='C').sum()
f=lambda x: f'{x:,}'.replace(',','.')
wa=(D.whatsapp!='').sum(); tel=(D.telefone!='').sum(); em=(D.email!='').sum(); site=(D.site!='').sum(); own=(D.cnpj!='').sum()
notes=[
f"O QUE É: as {f(n)} marcas brasileiras que registraram pelo menos um produto realmente novo na ANVISA entre 02/07 e 30/09/2026, nas categorias cabelo, rosto/skincare, corpo, sabonete, desodorante, maquiagem e perfume. Quem registra um produto está lançando: em média cerca de 80 dias antes de ele chegar à prateleira. Fonte: arquivo público da ANVISA (dados abertos de cosméticos), baixado em 04/10/2026.",
f"NOTAS: A ({f(A)}) = lançou 3 ou mais produtos, empresa pequena, dono identificado e com telefone ou WhatsApp: ligar primeiro. B ({f(B)}) = dono identificado e algum contato, lançamento menor ou dono a confirmar. C ({f(C)}) = dono não identificado (produto feito por fábrica terceirizada, ou registrado por empresa de importação ou de assuntos regulatórios), importadora, marca estrangeira ou empresa grande: use os links 'buscar' para achar o Instagram.",
"COMO TRABALHAR: mude a coluna Status a cada contato; o Painel atualiza sozinho. Em cada conversa, anote 'Gasto no último lançamento' e 'Comprou em 30 dias?': é isso que alimenta o teste das 20 conversas. Use os filtros da linha 1 (por nota, categoria, UF, status).",
"ORDEM DE CONTATO: 1) WhatsApp publicado no site da marca; 2) telefone; 3) e-mail. Comece perguntando 'quem é o dono ou a dona da marca?': muitas vezes quem atende é a distribuidora ou a fábrica.",
"CUIDADO COM CONTATOS DO CONTADOR: muitos telefones e e-mails do cadastro do CNPJ são do escritório de contabilidade ou do advogado. E-mails de contador ou advogado (domínios .cnt.br e .adv.br, 'contabilidade', 'jurídico', 'societário') nunca entram como contato principal. A planilha marca os prováveis ('PROVÁVEL CONTADOR', 'mesmo número em N empresas', 'DDD de outro estado') e nunca os coloca como contato principal. Telefones antigos de 8 dígitos receberam o 9 na frente.",
"FORMATO NÃO TESTADO: maquiagem e perfume estão na lista, marcados. O método do rótulo exato foi testado em frascos e tubos de cuidados; para essas marcas, ofereça a PRÉVIA antes de vender o pacote.",
"WHATSAPP: mande uma mensagem por vez, escrita por você. Nada de disparo em massa ou automação: o WhatsApp bloqueia o número.",
"LGPD (Lei 13.709/2018): os dados vêm de fontes públicas (ANVISA, cadastro CNPJ da Receita) e do que as próprias empresas publicam nos seus sites. Base: legítimo interesse para prospecção entre empresas (art. 7º, IX e art. 10), respeitando a finalidade e a boa-fé de dados de acesso público (art. 7º, §3º) e dados tornados públicos pelo titular (art. 7º, §4º). Na primeira mensagem, diga de onde veio o contato e ofereça sair da lista; quem pedir, marque 'Não contatar' e não procure de novo. Não compartilhe esta planilha fora do negócio.",
f"COMO A LISTA FOI FEITA: 1.203.659 registros de cosméticos na ANVISA → 29.984 notificações eletrônicas nos 90 dias → 22.534 nas sete categorias → 3.394 marcas com produto novo (re-registros de produtos antigos removidos) → {f(n)} depois de tirar multinacionais, grandes grupos, marcas estrangeiras e fornecedores de óleos essenciais. Dono: rodapé do site da marca, nome da empresa titular, ou titular que registra poucas marcas. Sites: endereços prováveis testados e conferidos (CNPJ ou produtos na página). Cadastro CNPJ: OpenCNPJ, BrasilAPI, minhareceita, CNPJá, ReceitaWS e publica.cnpj.ws (dados abertos da Receita).",
f"COBERTURA: dono identificado em {f(own)} marcas; site em {f(site)}; WhatsApp em {f(wa)}; telefone em {f(tel)}; e-mail em {f(em)}. LIMITES: o Instagram não pode ser lido sem login (use o link 'buscar no Instagram'); a nota de porte vem do cadastro e pode estar desatualizada; 'dono' marcado como 'confirme na ligação' é uma inferência.",
]
json.dump({'subtitle':f'{f(n)} marcas lançando produtos (ANVISA, 02/07–30/09/2026) · lista gerada em 05/10/2026 · A {f(A)} · B {f(B)} · C {f(C)}','notes':notes},open('meta.json','w'),ensure_ascii=False,indent=1)
print(json.load(open('meta.json'))['subtitle'])
