import pandas as pd, json
D=pd.read_pickle('final_all.pkl')
n=len(D); A=(D.grade=='A').sum(); B=(D.grade=='B').sum(); C=(D.grade=='C').sum()
f=lambda x: f'{x:,}'.replace(',','.')
bel=(D.mercado=='Beleza').sum(); sup=(D.mercado=='Suplementos').sum(); casa=(D.mercado=='Casa e aroma').sum()
anv=D.fonte.str.startswith('ANVISA').sum(); inpi=D.fonte.str.startswith('INPI').sum()
wa=(D.whatsapp!='').sum(); tel=(D.telefone!='').sum(); em=(D.email!='').sum(); site=(D.site!='').sum(); own=(D.cnpj!='').sum()
notes=[
f"O QUE É: {f(n)} marcas que estão lançando agora, de duas fontes públicas. (1) ANVISA: {f(anv)} marcas brasileiras de beleza que registraram pelo menos um produto realmente novo entre 02/07 e 30/09/2026 (cabelo, rosto/skincare, corpo, sabonete, desodorante, maquiagem e perfume); em média o produto chega à prateleira cerca de 80 dias depois. (2) INPI: {f(inpi)} marcas novas cujo pedido de registro foi publicado na Revista da Propriedade Industrial nº 2908 (29/09/2026): é o sinal mais cedo possível, muitas ainda não lançaram nada.",
f"MERCADOS: Beleza ({f(bel)}) é o mercado de agora. Suplementos ({f(sup)}) e Casa e aroma ({f(casa)}) são os próximos mercados: estão na lista para depois, não ligue para eles antes de terminar o teste das 20 conversas em Beleza. Use o filtro da coluna Mercado.",
f"NOTAS: A ({f(A)}) = lançou 3 ou mais produtos, empresa pequena, dono identificado e com contato: ligar primeiro. B ({f(B)}) = dono identificado e algum contato. C ({f(C)}) = sem contato ou dono não identificado (produto feito por fábrica terceirizada, importadora, marca estrangeira ou empresa grande): use os links 'buscar' para achar o Instagram. Marcas novas do INPI são B (com contato) ou C (sem contato).",
"MARCAS NOVAS DO INPI: quem pede a marca é o dono, então o dono é conhecido mesmo sem CNPJ. O CNPJ foi encontrado quando o titular é MEI (o número está no próprio nome), quando a empresa já aparece nas listas da ANVISA, ou quando o rodapé do site da marca mostra o CNPJ do mesmo titular. Abordagem: a marca ainda não lançou; ofereça a PRÉVIA antes do lançamento.",
"COMO TRABALHAR: mude a coluna Status a cada contato; o Painel atualiza sozinho. Em cada conversa, anote 'Gasto no último lançamento' e 'Comprou em 30 dias?': é isso que alimenta o teste das 20 conversas, que conta só o mercado Beleza. Use os filtros da linha 1 (por nota, mercado, categoria, UF, status).",
"ORDEM DE CONTATO: 1) WhatsApp publicado no site da marca; 2) telefone; 3) e-mail. Comece perguntando 'quem é o dono ou a dona da marca?': muitas vezes quem atende é a distribuidora ou a fábrica.",
"CUIDADO COM CONTATOS DO CONTADOR: muitos telefones e e-mails do cadastro do CNPJ são do escritório de contabilidade ou do advogado. E-mails de contador ou advogado (domínios .cnt.br e .adv.br, 'contabilidade', 'jurídico', 'societário') nunca entram como contato principal. A planilha marca os prováveis ('PROVÁVEL CONTADOR', 'mesmo número em N empresas', 'DDD de outro estado') e nunca os coloca como contato principal. Telefones antigos de 8 dígitos receberam o 9 na frente.",
"FORMATO NÃO TESTADO: maquiagem e perfume estão na lista, marcados. O método do rótulo exato foi testado em frascos e tubos de cuidados; para essas marcas, ofereça a PRÉVIA antes de vender o pacote.",
"WHATSAPP: mande uma mensagem por vez, escrita por você. Nada de disparo em massa ou automação: o WhatsApp bloqueia o número.",
"LGPD (Lei 13.709/2018): os dados vêm de fontes públicas (ANVISA, INPI, cadastro CNPJ da Receita) e do que as próprias empresas publicam nos seus sites. Base: legítimo interesse para prospecção entre empresas (art. 7º, IX e art. 10), respeitando a finalidade e a boa-fé de dados de acesso público (art. 7º, §3º) e dados tornados públicos pelo titular (art. 7º, §4º). Na primeira mensagem, diga de onde veio o contato e ofereça sair da lista; quem pedir, marque 'Não contatar' e não procure de novo. Não compartilhe esta planilha fora do negócio.",
f"COMO A LISTA FOI FEITA: ANVISA: 1.203.659 registros de cosméticos → 29.984 notificações eletrônicas nos 90 dias → 22.534 nas sete categorias → 3.394 marcas com produto novo (re-registros de produtos antigos removidos) → {f(anv)} depois de tirar multinacionais, grandes grupos, marcas estrangeiras e fornecedores de óleos essenciais. INPI: 11.894 pedidos de marca publicados na RPI 2908 → 602 de titulares brasileiros em cosméticos (classe 3), suplementos (classe 5) e velas/aromatizadores (classe 4) → {f(inpi)} depois de tirar grandes grupos, repetidos e marcas que já estavam na lista (essas ganharam um alerta). Sites: endereços prováveis testados e conferidos. Cadastro CNPJ: OpenCNPJ, BrasilAPI, minhareceita, CNPJá, ReceitaWS e publica.cnpj.ws (dados abertos da Receita).",
f"COBERTURA: dono identificado por CNPJ em {f(own)} marcas; site em {f(site)}; WhatsApp em {f(wa)}; telefone em {f(tel)}; e-mail em {f(em)}. LIMITES: o Instagram não pode ser lido sem login (use o link 'buscar no Instagram'); a nota de porte vem do cadastro e pode estar desatualizada; 'dono' marcado como 'confirme na ligação' é uma inferência; um pedido de marca no INPI não garante que o produto vai ser lançado.",
]
json.dump({'subtitle':f'{f(n)} marcas: {f(bel)} beleza · {f(sup)} suplementos · {f(casa)} casa e aroma · fontes ANVISA (02/07–30/09/2026) e INPI (RPI 2908, 29/09/2026) · gerada em 05/10/2026 · A {f(A)} · B {f(B)} · C {f(C)}','notes':notes},open('meta.json','w'),ensure_ascii=False,indent=1)
print(json.load(open('meta.json'))['subtitle'])
