# -*- coding: utf-8 -*-
"""Named contacts. Every entry sourced from an official governance page, a filing,
or a published quote. Nothing guessed. No email constructed from a pattern."""

# (name, role, org, conf, record, why_this_call)
CONTACTS = [
 ("THE TWO HIGHEST-LEVERAGE CALLS IN THE WHOLE EXERCISE", None, None, None, None, None),
 ("Elbia Gannoum", "Presidente Executiva", "ABEEólica", "H",
  "In post since 2011; also VP of GWEC. On Portaria 140, 22 Jul 2026: \"Hoje eu não sei dizer qual será o grau de adesão… essa será uma decisão individual de cada empresa.\" And on the mechanics: \"não haverá depósito em conta. Os valores serão abatidos de algo que as empresas teriam que pagar à CCEE.\"",
  "One call reaches ~40 member companies. She has publicly said adhesion is uncertain and company-by-company — that sentence IS the opening line. She is also the person who knows who is wavering."),
 ("Donato da Silva Filho", "CEO / Diretor-geral", "Volt Robotics", "H",
  "Near-monopoly supplier of the sector's curtailment loss data — every R$ figure in the Brazilian press traces to him. Tested MME's SOSIN formula and found it produces 143% MORE sobreoferta than ONS's own calculation.",
  "PARTNER OR COMPETITOR. He has the classification data and the credibility; he has no capital. Decide which he is before someone else does."),

 ("THE ABEEÓLICA BOARD ROSTER — each member company's own regulatory representative", None, None, None, None, None),
 ("(mandate Apr 2025 – Apr 2027)", "—", "ABEEólica Conselho", "H",
  "Presidenta Laura Cristina da Fonseca Porto (Neoenergia) · Fernando Elias Domingos Sé (Casa dos Ventos) · Bernardo Bezerra (Serena) · Francine Martins Pisni (Auren) · Leandro César Xavier de Carvalho (ENGIE) · Hugo Renato Anacleto Nunes (EDP) · Carolyne Muniz Dias (Voltalia) · Manoel de Andrade Lira Neto (Atlas) · Adelson Gomes Ferraz (Brennand) · Sandro Kiyoshi Yamamoto (Renova) · Sérgio Henrique Andrade de Azevedo (Dois A) · Gilberto Lourenço Feldman (PEC) · Thaisa Alcoforado de Almeida (EDF Power Solutions)",
  "This single page names the person at each member company who already owns this issue internally. It is the highest-yield contact source found anywhere in this research."),

 ("THE CURTAILMENT OWNER AT EACH MAJOR GENERATOR — call these, not the CEO", None, None, None, None, None),
 ("Fernando Elias Domingos Sé", "Diretor de Regulação e Comercialização", "Casa dos Ventos", "M",
  "Former Presidente do Conselho da ABEEólica; currently Casa dos Ventos' ABEEólica board representative. Title is 2025-vintage and may now be split with Itamar Lessa (Diretor de Comercialização).",
  "Largest single holder of eligible claim in Brazil (18.8% of the pool). Privately held, so no analyst has done this work for them."),
 ("Priscila Rochinha Lino", "Diretora Regulatório e Planejamento Energético", "Auren Energia", "H",
  "The ONS/ANEEL/CCEE owner at Auren. Separately: \"Auren projeta receber R$250 mi com ressarcimento por curtailment\" — Agência iNFRA, 14 Nov 2025.",
  "Auren has PUBLICLY PUT A NUMBER ON WHAT IT EXPECTS TO RECEIVE. That makes it the single best-quantified conversation available — you can open with their own figure."),
 ("Gabriel Mann dos Santos", "Diretor de Regulação, Estratégia e Comunicação", "Engie Brasil Energia", "H",
  "Curtailment owner. CEO Eduardo Sattamini, NeoFeed 26 May 2026: \"A Engie não deve investir em nova capacidade intermitente até termos uma visibilidade de que o sistema precisa dessa energia.\" ~17% of output cut.",
  "Engie discloses curtailment only in percentages and has never published an R$ figure. The gap between what they know and what they say is the opening."),
 ("Cristiano de Lima Logrado", "Diretor de Regulação e Mercado", "Equatorial Energia", "H",
  "The ANEEL/ONS/CCEE operator for the whole group INCLUDING Echoenergia. Has signed formal group letters to ANEEL. CFO Leonardo Lima: curtailment costs ~R$900m, group evaluating divestments; 4Q25 525 GWh constrained-off at a 27.4% restriction rate.",
  "One call covers both Equatorial and Echoenergia — and Echoenergia is already plaintiff in two of the twelve lawsuits."),
 ("Liu Aquino", "Diretor-Presidente", "Echoenergia", "H",
  "Elected Jan 2024. 51.4% solar curtailment — worst among the majors. NeoFeed 2 Oct 2025: \"Os sinais econômicos do setor estão distorcidos diante desse cenário de curtailment da geração centralizada.\" Invited to testify at the Câmara dos Deputados hearing on curtailment, 17 Dec 2025.",
  "The most-quoted operator in Brazil on this issue, and already litigating. He has to actively choose to abandon those suits."),
 ("Anna Paula Hiotte Pacheco", "Diretora de Regulação", "Enel Brasil", "H",
  "In role since Jul 2018 — eight years. Previously Diretora de Regulação Brasil e Uruguai at Enel Green Power Brasil. Sits on the boards of both ABEEólica and APINE.",
  "Longest-tenured regulatory director in the set and sits on both association boards. Decision may still need Rome, but she is where it starts."),
 ("Gustavo Andrioli", "VP Sr. Jurídico, Regulatório e de Compliance", "Elera Renováveis (Brookfield)", "H",
  "Combined GC and regulatory — a single call covers both. \"Com 23% da geração cortada, Elera aguarda solução definitiva para o curtailment\" — MegaWhat, 10 Nov 2025. CEO Karin Luchesi since May 2025; CFO José Simão.",
  "Elera holds an actual injunction (6ª Vara Federal DF, 18 Feb 2025, Complexo Alex, >R$46m protected) — so it has the most to surrender by signing. Highest-stakes waiver decision in the market."),
 ("Solange Maria Pinto Ribeiro", "Diretora VP de Regulação, Institucional e Sustentabilidade", "Neoenergia (Iberdrola)", "H",
  "Curtailment owner — there is no standalone Diretor de Regulação. Note Neoenergia reorganised in April 2026: CFO+DRI is now Carlos Henrique Quadros Choqueta after Leonardo Gadelha resigned. Any contact list older than May 2026 is wrong.",
  "Neoenergia is predominantly ACR/auction-contracted, so its compensation is more likely book entry than cash. Good advisory target, poor financing target."),
 ("Hugo Renato Anacleto Nunes", "Diretor Executivo de Regulação, EDP América do Sul", "EDP Brasil", "H",
  "Appointed 4 Dec 2025 — the freshest and most on-point contact in the set. Also EDP's ABEEólica board representative. Group president João Brito Martins since Jun 2025.",
  "New in role, so still forming his position. EDP delisted in 2023 and has no active Brazilian IR function, which means no analyst is pressing them on this."),
 ("Rodrigo Limp Nascimento", "VP Executivo de Regulação, Institucional e Mercado", "AXIA Energia (ex-Eletrobras)", "H",
  "FORMER ANEEL DIRETOR-GERAL. Note the company rebranded from Eletrobras to AXIA — any list still saying Eletrobras is stale. Chesf, the Northeast entity, is led by Antonio Varejão de Godoy.",
  "The highest-value regulatory call among the incumbents. He has sat on the other side of this exact rule. Not a sales call — an intelligence call."),
 ("André Luiz Gomes da Silva", "VP de Regulação e Mercado", "Copel", "H",
  "Appointed Nov 2024, term to 2026. Copel ran 37.4% wind curtailment in Q4 2025 per BTG.", "Privatised in 2023, no controlling shareholder — decisions are commercial rather than political."),

 ("FINANCE — for when the conversation turns to the cash-versus-book-entry question", None, None, None, None, None),
 ("Andrea Sztajn", "Diretora Financeira e de Relações com Investidores", "Serena Energia", "H",
  "CFO and DRI in one. At Omega/Serena since 2014; DRI since Sep 2024. Fitch: R$200m of 2025 EBITDA impact, 11% of total — the highest proportional hit of any rated name. Now controlled by Actis + GIC and delisting.",
  "Serena is the most litigious name in the set — ANEEL denied its reclassification request in Feb 2025. She owns both the number and the decision."),
 ("Mateus Gomes Ferreira", "VP de Finanças e Relações com Investidores", "Auren Energia", "H",
  "Moved from Chairman to CFO+DRI on 1 Jul 2024. Has said publicly Auren has entered \"a period of leverage stability\" with deleveraging resuming only from 2027. FY2025 net loss R$557.9m; 1Q26 net loss R$601.6m; net debt/EBITDA back to 5.2x.",
  "Fitch revised Auren's outlook to Negative on 10 Jul 2026 citing curtailment at ~R$520m/year. The timing pressure is real and public."),
 ("Rafael Sanchez Brandão", "CFO, DRI and Chairman", "Rio Alto Energia", "H",
  "Holds all three roles. CAUTION: a CVM Termo de Compromisso was accepted in Oct 2024 against both him and CEO Edmond Chaker Farhat Junior. Know this before calling.",
  "The one acute name — extrajudicial recovery extinguished June 2026, BTG enforcing Santa Luzia 5/7/9, sale mandated by end-2026, no buyer. It cannot survive to collect. Advisory only; this is not a lending situation."),
 ("Fernando Guedes Vieira", "Diretor Presidente, VP Jurídico e DRI", "2W Ecobank", "H",
  "Elected 22 Apr 2026, mandate to 2029, covering four of the six relevant roles. IN RECUPERAÇÃO JUDICIAL — plan homologated by cram down Dec 2025, ~R$2.6bn. Judicial administrator: Vivante.",
  "Your only contact there. Do NOT call from stale lists — Rolim, Coutinho, Pereira, Aguiar and Berenguer all departed in Apr 2026."),

 ("THE OTHER ASSOCIATION, AND THE REGIONAL VOICES", None, None, None, None, None),
 ("Rodrigo Lopes Sauaia", "Presidente Executivo", "ABSOLAR", "H",
  "Co-founder. Has warned repeatedly on judicialisation persisting after Portaria 140 (MegaWhat, 23 Jul 2026), and that MME gave no sufficiently clear criteria for classifying cut types. Superintendente: Celina Araújo.",
  "The solar counterpart to Gannoum. ABSOLAR's public read — that the manifestação does not itself waive existing suits — is the one that matters most to our thesis."),
 ("Isabella Sene", "Técnico e Regulatório (TECREG)", "ABSOLAR", "H",
  "ABSOLAR publishes no 'diretor regulatório' title; regulatory work sits in the TECREG team. Source of the R$2.8bn centralised-solar ACR figure for 2025.",
  "The working-level regulatory contact. NOTE: 'Talita Porto, Diretora Técnico-Regulatória' appears in search results but is NOT on the current staff page — do not use that name."),
 ("Sérgio Azevedo / Darlan Santos", "Presidente, COERE-FIERN / Presidente, Cerne", "Regional (RN)", "H",
  "Both warned publicly on 22 Jul 2026 that overgeneration cuts — the most recurrent in the Northeast — are expressly excluded, and that signing bars contesting the classification.",
  "They have already made our central argument in public. Rio Grande do Norte is 44% of the eligible pool, so these are the right regional doors."),

 ("HOW TO USE THIS SHEET", None, None, None, None, None),
 ("Call the regulatory director, not the CEO", "—", "—", "—",
  "In almost every company above there is one named person who owns ONS/ANEEL/CCEE matters. That is who understands the classification question, and that is who will recognise within thirty seconds whether you have read the Termo or a law firm summary.",
  "The CEO call comes second, after the regulatory director has validated that the question is real."),
 ("No email addresses are constructed here", "—", "—", "—",
  "Every name is from an official governance page, a CVM filing, or a published quote. NO EMAIL HAS BEEN BUILT FROM A PATTERN. Published department inboxes exist for Engie, Enel, Neoenergia, Voltalia, Rio Alto, Copel, Cemig and AXIA; the Apollo contact database returned a billing error on this account and was not used.",
  "Route in through GC's network. Where there is no route, the association call is the way in."),
 ("Confidence and staleness", "—", "—", "—",
  "H = on an official governance page or in a filing. M = published title but 2025-vintage or from a conference listing. Several companies reorganised recently — Neoenergia in Apr 2026, Engie Jul 2025, 2W Apr 2026, Eletrobras rebranded to AXIA. Verify the title before you use it in a first sentence.",
  "A wrong title in the first sentence costs more than not knowing the name."),
 ("Where nobody could be found", "—", "—", "—",
  "No name was found for: Casa dos Ventos CFO and GC; Serena regulatory and commercial directors; Voltalia Brasil CFO and regulatory; Rio Energy and Essentia entire boards; Furnas (site returns errors); Bolt, Newave, Solatio, Lightsource bp Brasil, Canadian Solar Brasil; and named partners at Pátria, Perfin, Prisma, Mubadala and BTG.",
  "These are gaps, not absences. GC's network will close most of them faster than any search could."),
]
